name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Use your preferred Node.js version

      - name: Install dependencies
        run: yarn install  # or npm install

      - name: Start the app (deployment step)
        run: yarn start  # or npm start

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/v1/services/srv-cvco75bv2p9s73ekf5dg/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'
